version: "2"

services:
  image:
    build: "."
    image: stefanfoulis/timelapseapp-ui:local
    command: "true"

  base: &BASE
    image: stefanfoulis/timelapseapp-ui:local
    depends_on:
      - "image"
    command: bash
    volumes:
      - ".:/app:delegated"

  cli:
    <<: *BASE
    command: ash

  web:
    <<: *BASE
    command: yarn start
    ports:
      - "8054:80"
    environment:
      REACT_APP_BACKEND_ENDPOINT: https://timelapseapp-backend.local.foul.is/graphql/
      VIRTUAL_HOST: timelapseapp-ui.local.foul.is
