version: "2"

services:
  base_build:
    build: "."
    image: stefanfoulis/timelapseapp-ui:local
    command: "true"

  base: &BASE
    image: stefanfoulis/timelapseapp-ui:local
    depends_on:
      - "base_build"
    command: bash
    volumes:
      - "timelapseapp-ui-src-sync:/app:nocopy"

  web:
    <<: *BASE
    command: npm start
    environment:
      VIRTUAL_HOST: timelapseapp-ui.divio.me

volumes:
  timelapseapp-ui-src-sync:
    external: true
